UPDATE sys.props$ SET value$='YYYY-MM-DD' WHERE name='NLS_DATE_FORMAT';
UPDATE sys.props$ SET value$='HH24:MI:SSXFF' WHERE name='NLS_TIME_FORMAT';
UPDATE sys.props$ SET value$='YYYY-MM-DD HH24:MI:SSXFF' WHERE name='NLS_TIMESTAMP_FORMAT';
UPDATE sys.props$ SET value$='HH24:MI:SSXFF TZR' WHERE name='NLS_TIME_TZ_FORMAT';
UPDATE sys.props$ SET value$='YYYY-MM-DD HH24.MI.SSXFF TZR' WHERE name='NLS_TIMESTAMP_TZ_FORMAT';
exit
